providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir -r requirements-production.txt"
]
