services:
  - type: web
    name: funzamama-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --interface wsgi --workers 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PREFERRED_URL_SCHEME
        value: https

databases:
  - name: funzamama-db
    plan: free
